- name: "install python-httplib2"
  apt:
    pkg: "python-httplib2"

- name: "check elasticsearch version"
  uri:
    url: "http://{{ es_server_ip }}:{{ es_server_port}}"
    return_content: "yes"
  register: "es_response"

- set_fact:
    es_output: "{{ es_response.content|from_json }}"
- set_fact:
    es_version: "{{ es_output.version.number }}"

- debug:
    msg: "ES version number is {{ es_version }}"

- fail:
    msg: "ES version <1.0. Repos/Snapshots not supported"
  when: 
    - es_version | version_compare('1.0', '<') 

- debug:
    msg: "ES version >1.6 . path.repo required"
  when:
    -  es_version | version_compare('1.6', '>=') 

- name: "add path.repo var to elasticsearch.yml"
  lineinfile:
    dest: "/etc/elasticsearch/elasticsearch.yml"
    regexp: "^path.repo:"
    line: "path.repo: [\"{{ es_path_repo }}\"]"
    backup: "yes"
    owner: "elasticsearch"
    group: "elasticsearch"
  when: 
    - es_version | version_compare('1.6', '>=') 
  notify: "restart elasticsearch"
- name: "flush to restart elasticsearch if there were config changes"
  meta: "flush_handlers"

- name: "wait until elasticsearch port is open (to avoid errors when it was restarted)"
  wait_for:
    host: "{{ es_server_ip }}"
    port: "{{ es_server_port }}"

- name: "add repository to elasticsearch"
  uri:
    url: "http://{{ es_server_ip }}:{{ es_server_port }}/_snapshot/{{ es_repo_name }}"
    method: "PUT"
    body:
      type: "fs"
      settings:
        location: "{{ es_path_repo }}"
    body_format: "json"
